// <auto-generated />
using System;
using Infrastructure.Data.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations.Domain
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20230320114115_ChangeFormAndControls")]
    partial class ChangeFormAndControls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormSubmitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Answer", "domain");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Answer");
                });

            modelBuilder.Entity("Domain.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserAuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DomainUsers", "domain");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            Email = "seed1.df@gmail.com",
                            IsDeleted = false,
                            UserAuthId = new Guid("4c177013-3086-4f27-b700-bf02c1f327dc"),
                            UserName = "seed1.df@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            Email = "seed2.df@gmail.com",
                            IsDeleted = false,
                            UserAuthId = new Guid("44eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            UserName = "seed2.df@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            Email = "seed3.df@gmail.com",
                            IsDeleted = false,
                            UserAuthId = new Guid("407f9516-94bd-4251-8756-822a582e7df6"),
                            UserName = "seed3.df@gmail.com"
                        });
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Forms", "domain");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b58c4b9e-fb23-4aab-a533-de333ca937bd"),
                            CreatorId = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8889), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8918), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed1.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("a4c4b2aa-fc71-4e03-bbb8-070a092b6cc2"),
                            CreatorId = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8952), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8954), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed1.df Form2",
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("c827d496-ade7-42fa-8a89-d5bfda486311"),
                            CreatorId = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8959), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8960), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed1.df Form3",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("99cf0f88-4351-4fec-a652-185bec7b2aad"),
                            CreatorId = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8985), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8984), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed2.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("75c77e51-148d-414d-9100-f5e095439405"),
                            CreatorId = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8989), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8990), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed2.df Form1",
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("e00a859d-1fb4-45ab-b67a-6f557aa97724"),
                            CreatorId = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8997), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(8999), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed2.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("69501010-eb7f-4e7f-85be-199ba6aaaf63"),
                            CreatorId = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(9055), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(9057), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed3.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("4301d900-cd0b-4b17-b166-58b7d7c73c5b"),
                            CreatorId = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(9061), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(9062), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed3.df Form1",
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("6973efcf-4ab5-4af1-a0d2-e7b2b21e5646"),
                            CreatorId = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(9065), new TimeSpan(0, 3, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 3, 20, 14, 41, 14, 979, DateTimeKind.Unspecified).AddTicks(9067), new TimeSpan(0, 3, 0, 0, 0)),
                            Domain = "seed",
                            IsDeleted = false,
                            Name = "Seed seed3.df Form1",
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("DateSubmitted")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmits", "domain");
                });

            modelBuilder.Entity("Domain.PrivateFormAccessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AccessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccessorId");

                    b.HasIndex("FormId");

                    b.ToTable("PrivateFormAccessors", "domain");
                });

            modelBuilder.Entity("Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Question", "domain");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");
                });

            modelBuilder.Entity("Domain.InputAnswer", b =>
                {
                    b.HasBaseType("Domain.Answer");

                    b.Property<Guid>("InputQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FormSubmitId");

                    b.HasIndex("InputQuestionId");

                    b.HasDiscriminator().HasValue("InputAnswer");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.HasBaseType("Domain.Question");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("InputQuestion");
                });

            modelBuilder.Entity("Domain.SelectAnswer", b =>
                {
                    b.HasBaseType("Domain.Answer");

                    b.Property<Guid>("SelectQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FormSubmitId");

                    b.HasIndex("SelectQuestionId");

                    b.HasDiscriminator().HasValue("SelectAnswer");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.HasBaseType("Domain.Question");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectType")
                        .HasColumnType("int");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("SelectQuestion");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.HasOne("Domain.DomainUser", "Creator")
                        .WithMany("CreatedForms")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("FormSubmits")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.DomainUser", "User")
                        .WithMany("FormSubmits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.PrivateFormAccessor", b =>
                {
                    b.HasOne("Domain.DomainUser", "Accessor")
                        .WithMany("AccessedPrivateForms")
                        .HasForeignKey("AccessorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Form", "Form")
                        .WithMany("Accessors")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accessor");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.InputAnswer", b =>
                {
                    b.HasOne("Domain.FormSubmit", "FormSubmit")
                        .WithMany("InputAnswers")
                        .HasForeignKey("FormSubmitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.InputQuestion", "InputQuestion")
                        .WithMany("InputAnswers")
                        .HasForeignKey("InputQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormSubmit");

                    b.Navigation("InputQuestion");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("InputQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.SelectAnswer", b =>
                {
                    b.HasOne("Domain.FormSubmit", "FormSubmit")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("FormSubmitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SelectQuestion", "SelectQuestion")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("SelectQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormSubmit");

                    b.Navigation("SelectQuestion");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("SelectQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.DomainUser", b =>
                {
                    b.Navigation("AccessedPrivateForms");

                    b.Navigation("CreatedForms");

                    b.Navigation("FormSubmits");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Navigation("Accessors");

                    b.Navigation("FormSubmits");

                    b.Navigation("InputQuestions");

                    b.Navigation("SelectQuestions");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.Navigation("InputAnswers");

                    b.Navigation("SelectAnswers");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.Navigation("InputAnswers");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.Navigation("SelectAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
