// <auto-generated />
using System;
using Infrastructure.Data.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations.Domain
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20230113124142_SeedFormsAndUsers")]
    partial class SeedFormsAndUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormSubmitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Answer", "domain");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Answer");
                });

            modelBuilder.Entity("Domain.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserAuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DomainUsers", "domain");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            Email = "seed1.df@gmail.com",
                            IsDeleted = false,
                            UserAuthId = new Guid("4c177013-3086-4f27-b700-bf02c1f327dc"),
                            UserName = "seed1.df@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            Email = "seed2.df@gmail.com",
                            IsDeleted = false,
                            UserAuthId = new Guid("44eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            UserName = "seed2.df@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            Email = "seed3.df@gmail.com",
                            IsDeleted = false,
                            UserAuthId = new Guid("407f9516-94bd-4251-8756-822a582e7df6"),
                            UserName = "seed3.df@gmail.com"
                        });
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Forms", "domain");

                    b.HasData(
                        new
                        {
                            Id = new Guid("778ec6b7-14f0-4e15-8488-c241155c8289"),
                            CreatorId = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(787), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed1.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("849244b4-c480-4d25-a831-4df7b6e138ef"),
                            CreatorId = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(849), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed1.df Form2",
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("12147df3-0241-419a-8985-53f9ceb2aecd"),
                            CreatorId = new Guid("3c177013-3086-4f27-b700-bf02c1f327dc"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(855), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed1.df Form3",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("a62b4d3a-ce6d-4284-98a9-ccf05481635d"),
                            CreatorId = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(859), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed2.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("0c087839-80fd-4511-a356-511d749d783b"),
                            CreatorId = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(864), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed2.df Form1",
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("87573e3d-061c-485d-9110-3b25dce3d62e"),
                            CreatorId = new Guid("e4eb0b1c-3cda-4548-a5bf-7dcc79cf9a4c"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(870), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed2.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("854db5e4-3c90-4c53-8217-3b9327dd968f"),
                            CreatorId = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(874), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed3.df Form1",
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("57310ddc-32d8-4b37-9024-289206aa23ed"),
                            CreatorId = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(877), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed3.df Form1",
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("79944443-890f-4acf-a541-faf2e5c8ee98"),
                            CreatorId = new Guid("f07f9516-94bd-4251-8756-822a582e7df6"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 1, 13, 15, 41, 42, 495, DateTimeKind.Unspecified).AddTicks(899), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Seed seed3.df Form1",
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("DateSubmitted")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmits", "domain");
                });

            modelBuilder.Entity("Domain.PrivateFormAccessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AccessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccessorId");

                    b.HasIndex("FormId");

                    b.ToTable("PrivateFormAccessors", "domain");
                });

            modelBuilder.Entity("Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Question", "domain");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");
                });

            modelBuilder.Entity("Domain.InputAnswer", b =>
                {
                    b.HasBaseType("Domain.Answer");

                    b.Property<Guid>("InputQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FormSubmitId");

                    b.HasIndex("InputQuestionId");

                    b.HasDiscriminator().HasValue("InputAnswer");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.HasBaseType("Domain.Question");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("InputQuestion");
                });

            modelBuilder.Entity("Domain.SelectAnswer", b =>
                {
                    b.HasBaseType("Domain.Answer");

                    b.Property<Guid>("SelectQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FormSubmitId");

                    b.HasIndex("SelectQuestionId");

                    b.HasDiscriminator().HasValue("SelectAnswer");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.HasBaseType("Domain.Question");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("bit");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("SelectQuestion");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.HasOne("Domain.DomainUser", "Creator")
                        .WithMany("CreatedForms")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("FormSubmits")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.DomainUser", "User")
                        .WithMany("FormSubmits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.PrivateFormAccessor", b =>
                {
                    b.HasOne("Domain.DomainUser", "Accessor")
                        .WithMany("AccessedPrivateForms")
                        .HasForeignKey("AccessorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Form", "Form")
                        .WithMany("Accessors")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accessor");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.InputAnswer", b =>
                {
                    b.HasOne("Domain.FormSubmit", "FormSubmit")
                        .WithMany("InputAnswers")
                        .HasForeignKey("FormSubmitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.InputQuestion", "InputQuestion")
                        .WithMany("InputAnswers")
                        .HasForeignKey("InputQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormSubmit");

                    b.Navigation("InputQuestion");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("InputQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.SelectAnswer", b =>
                {
                    b.HasOne("Domain.FormSubmit", "FormSubmit")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("FormSubmitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SelectQuestion", "SelectQuestion")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("SelectQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormSubmit");

                    b.Navigation("SelectQuestion");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("SelectQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.DomainUser", b =>
                {
                    b.Navigation("AccessedPrivateForms");

                    b.Navigation("CreatedForms");

                    b.Navigation("FormSubmits");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Navigation("Accessors");

                    b.Navigation("FormSubmits");

                    b.Navigation("InputQuestions");

                    b.Navigation("SelectQuestions");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.Navigation("InputAnswers");

                    b.Navigation("SelectAnswers");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.Navigation("InputAnswers");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.Navigation("SelectAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
