// <auto-generated />
using System;
using Infrastructure.Data.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations.Domain
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20230103114529_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormSubmitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Answer", "domain");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Answer");
                });

            modelBuilder.Entity("Domain.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserAuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DomainUsers", "domain");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Forms", "domain");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("DateSubmitted")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmits", "domain");
                });

            modelBuilder.Entity("Domain.PrivateFormAccessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AccessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccessorId");

                    b.HasIndex("FormId");

                    b.ToTable("PrivateFormAccessors", "domain");
                });

            modelBuilder.Entity("Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Question", "domain");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");
                });

            modelBuilder.Entity("Domain.InputAnswer", b =>
                {
                    b.HasBaseType("Domain.Answer");

                    b.Property<Guid>("InputQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FormSubmitId");

                    b.HasIndex("InputQuestionId");

                    b.HasDiscriminator().HasValue("InputAnswer");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.HasBaseType("Domain.Question");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("InputQuestion");
                });

            modelBuilder.Entity("Domain.SelectAnswer", b =>
                {
                    b.HasBaseType("Domain.Answer");

                    b.Property<Guid>("SelectQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FormSubmitId");

                    b.HasIndex("SelectQuestionId");

                    b.HasDiscriminator().HasValue("SelectAnswer");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.HasBaseType("Domain.Question");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("bit");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("SelectQuestion");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.HasOne("Domain.DomainUser", "Creator")
                        .WithMany("CreatedForms")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("FormSubmits")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.DomainUser", "User")
                        .WithMany("FormSubmits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.PrivateFormAccessor", b =>
                {
                    b.HasOne("Domain.DomainUser", "Accessor")
                        .WithMany("AccessedPrivateForms")
                        .HasForeignKey("AccessorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Form", "Form")
                        .WithMany("Accessors")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accessor");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.InputAnswer", b =>
                {
                    b.HasOne("Domain.FormSubmit", "FormSubmit")
                        .WithMany("InputAnswers")
                        .HasForeignKey("FormSubmitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.InputQuestion", "InputQuestion")
                        .WithMany("InputAnswers")
                        .HasForeignKey("InputQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormSubmit");

                    b.Navigation("InputQuestion");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("InputQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.SelectAnswer", b =>
                {
                    b.HasOne("Domain.FormSubmit", "FormSubmit")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("FormSubmitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SelectQuestion", "SelectQuestion")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("SelectQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormSubmit");

                    b.Navigation("SelectQuestion");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("SelectQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Domain.DomainUser", b =>
                {
                    b.Navigation("AccessedPrivateForms");

                    b.Navigation("CreatedForms");

                    b.Navigation("FormSubmits");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Navigation("Accessors");

                    b.Navigation("FormSubmits");

                    b.Navigation("InputQuestions");

                    b.Navigation("SelectQuestions");
                });

            modelBuilder.Entity("Domain.FormSubmit", b =>
                {
                    b.Navigation("InputAnswers");

                    b.Navigation("SelectAnswers");
                });

            modelBuilder.Entity("Domain.InputQuestion", b =>
                {
                    b.Navigation("InputAnswers");
                });

            modelBuilder.Entity("Domain.SelectQuestion", b =>
                {
                    b.Navigation("SelectAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
